- packages/azure/package.json
- packages/mssql/package.json
- packages/redis/package.json
- packages/s3/package.json
- yarn.lock
Travis was reporting success on failed integration tests. This change fixes the issue.
The reason for the failure was that the yarn integrate command:
`docker-compose up -d && jest <...>; docker-compose down`
exits with the exit code from the docker-compose down command instead of the jest one.
The following modified version temporarily stores the exit code from jest and exits with it at the end:
`docker-compose up -d && jest <...>; R=$?; docker-compose down; bash -c "exit $R"`
> Integration command exits with jest exit code

- packages/kafka/package.json
- packages/kafka/src/__test__/KafkaNonTransactional.integration.test.ts
The `triggers a rebalance after staggering the joining of a second consumer.` integration test was failing because it was expecting the wrong number of message reprocessing to happen.
> Fix failing Kafka integration test

- packages/kubernetes/package.json
- yarn.lock
#48 on the develop branches uses a git commit from master of the [`kubernetes/client-node`](https://github.com/kubernetes-client/javascript) package which isn't ideal. `0.11.1` was just recently released so we can update to that version which has the fix we were looking for. This should also help to alleviate some of the intermittent build issues we've been seeing where [Yarn is unable to find a package](https://github.com/yarnpkg/yarn/issues/2629) during install.
> kubernetes: update @kubernetes/client-node package to 0.11.1

- packages/core/package.json
- packages/core/src/__test__/defaults/ConsoleLogger.test.ts
- packages/core/src/defaults/ConsoleLogger.ts
The console logger renders out `[object Object]` if a field is an object so destructure it into `.` delimited nested fields (e.g. foo.bar.baz)
> core: update ConsoleLogger to correctly log out nested objects

- packages/azure/package.json
- packages/azure/src/streaming/index.ts
- packages/azure/src/streaming/internal/QueueInputSource.ts
- packages/azure/src/streaming/internal/config.ts
- packages/azure/src/utils/QueueClient.ts
This PR is to start a conversation around how to allow us to consume any message from the azure storage queue.  This will hopefully resolve 2 issues:
1.  Message text is Base64 encoded and thus fails JSON.parse call.  We need to be able to specify QueueMessageEncoder for QueueService.messageEncoder
2. Messages may not have header and payload, so in this case need a generic header with messageText as the payload.
> Add preprocessor concept for Azure Queues to support messages not following the envelope format

- packages/core/package.json
- packages/core/src/__test__/utils/BoundedPriorityQueue.test.ts
- packages/core/src/utils/BoundedPriorityQueue.ts
It's possible to get into a state where we've hit our limit on items
that we can add to the bounded priority queue and a large backlog of
items are accumulated. Once we can begin to process that backlog after
a `whenNotFull` promise resolves, the first item in the backlog will
create a new `whenNotFull` and proceed to await it. Subsequent items in
backlog queue will do the same but overwrite the promise of the first
item leading to a chain of promises for backlogged items that are
unresolvable. This PR ensures that we never overwrite the
`whenNotFull` promise for backlogged queue items and we can resolve
them all eventually.
> support multiple concurrent writers for BoundedPriorityQueue

- packages/core/package.json
- packages/core/src/__test__/utils/BoundedPriorityQueue.test.ts
- packages/core/src/utils/BoundedPriorityQueue.ts
It's possible to get into a state where we've hit our limit on items
that we can add to the bounded priority queue and a large backlog of
items are accumulated. Once we can begin to process that backlog after
a `whenNotFull` promise resolves, the first item in the backlog will
create a new `whenNotFull` and proceed to await it. Subsequent items in
backlog queue will do the same but overwrite the promise of the first
item leading to a chain of promises for backlogged items that are
unresolvable. This PR ensures that we never overwrite the
`whenNotFull` promise for backlogged queue items and we can resolve
them all eventually.
> core: support multiple concurrent writers for BoundedPriorityQueue

- packages/core/package.json
- packages/core/src/__test__/utils/BoundedPriorityQueue.test.ts
- packages/core/src/utils/BoundedPriorityQueue.ts
core: fix issue with bounded priority queue not correctly supporting closing of queues
immediately after it was drained leading to potential `Cannot read
property 'resolve' of undefined` errors due to whenNotFull being
undefined.
> core: unable to close bounded priority queue

- packages/azure/package.json
- packages/azure/src/streaming/index.ts
- packages/azure/src/streaming/internal/config.ts
- packages/core/package.json
- packages/core/src/__test__/config.test.ts
- packages/core/src/config.ts
The API contract of Azure Queue's was changed to accept milliseconds instead of seconds as part of a bugfix in 1.2. This PR reverts the breaking API change and restores semver compatibility.
> Fix breaking API change in Azure Queues

- packages/core/package.json
- packages/core/src/internal/processor/ConcurrentMessageProcessor.ts
When message handling fails outside of the message handler the ConcurrentMessageHandler currently throws a generic Error that hides the underlying root cause error. This PR changes it to re-throw the original error, similar to what the SerialMessageProcessor is doing.
> ConcurrentMessageProcessor suppresses error details

- packages/redis/package.json
do version bump missing in PR #126
> Bump Redis version to publish new package

- packages/core/package.json
- packages/core/src/config.ts
This is a workaround until #96 is fixed
> Prevent config.parse() output from being used as input

- packages/azure/package.json
- packages/azure/src/__test__/event-sourced/internal/CosmosStateAggregationSource.test.ts
- packages/azure/src/__test__/materialized/internal/MaterializedView.integration.test.ts
- packages/azure/src/__test__/utils/helpers.test.ts
- packages/azure/src/index.ts
- packages/azure/src/materialized/internal/CosmosStateProvider.ts
- packages/azure/src/utils/CosmosClient.ts
- packages/azure/src/utils/helpers.ts
Adds support for multiple cosmos collections
- keys must be provided in the format  "@collection/key" or "key"
- collectionIds are optional
> multi cosmos collections (#81)

- packages/core/package.json
- packages/core/src/__test__/utils/BoundedPriorityQueue.test.ts
- packages/core/src/internal/processor/ConcurrentMessageProcessor.ts
- packages/core/src/internal/processor/RpcMessageProcessor.ts
- packages/core/src/utils/BoundedPriorityQueue.ts
Also move the in flight requests value into its own gauge for Concurrent parallelism mode.
> Prevent BoundedPriorityQueue from deprioritizing waiting enqueue calls

- packages/kafka/package.json
- packages/kafka/src/KafkaConsumer.ts
watermarks are only loaded so they can be exposed as metrics. failure to do so has no effect on the message processing flow.
> Change LogLevel from Error -> Warn when retrieving Kafka watermarks

- packages/kafka/package.json
- packages/kafka/src/KafkaConsumer.ts
This PR detects stale metadata cached in kafkajs and forces the application terminate as it currently gets stuck in an infinite error/retry loop. This is only intended to be a workaround until the underlying root cause has been addressed.
Only planning to merge this if needed
> detect when kafkajs is stuck with stale broker metadata

- packages/redis/package.json
- packages/redis/src/RedisClient.ts
Several public functions on RedisClient take a `type: string | IClassType<T>` but do not validate that the given `type` is a string before attempting to use it as a metric label. When using the Prometheus exporter I recently observed the following value for the "type" label on a service's `/metrics` endpoint:
```
kepler_cookie_cutter_redis_client_get{type="function DomainType(properties) {
this.domainArray1 = [];
this.domainArray2 = [];
if (properties)
for (var keys = Object.keys(properties), i = 0; i < keys.length; ++i)
if (properties[keys[i]] != null)
this[keys[i]] = properties[keys[i]];
}",db="0",result="success"} 5951 1601386579347
```
The Cookie Cutter Prometheus package also logs the following warning when this happens:
```json
{"msg":"Prometheus Labels of Type other than string or …
```
> Ensure RedisClient's "type" metric label is always a string

- packages/gcp/package.json
- packages/gcp/src/BigQueryClient.ts
- packages/gcp/src/GcsClient.ts
Currently the entire Error object is being passed to metrics. Change it to pass only the error string.
> Fix: pass string error message to metrics 

- packages/kafka/package.json
- packages/kafka/src/KafkaConsumer.ts
- packages/kafka/src/KafkaMessageProducer.ts
- packages/kafka/src/KafkaSink.ts
- packages/kafka/src/config.ts
- packages/kafka/src/index.ts
- packages/kafka/src/utils.ts
~According to the [KafkaJS docs](https://kafka.js.org/docs/producing#a-name-compression-a-compression) we wouldn't be able to support compression modes other than Gzip without taking on a new dependency.~
Edit: `cookie-cutter-kafka` already depends on the Snappy and LZ4 KafkaJS compression plugins, so those will be supported as part of this PR as well.
> [kafka] Expose compression settings for producers via kafkaSink

- packages/redis/package.json
- packages/redis/src/RedisProxy.ts
Redis stream consumers frequently get stuck consuming the stream when the connection to Redis is lost. Even though the logs indicate the connection was re-established, no new messages are flowing in anymore. As a quick fix we are forcing the application to terminate on disconnect.
This closes #206
> force application to restart on redis disconnect

- package.json
- packages/gcp/package.json
As part of the effort to fix ongoing issues with `task-response-uploader-gcp` service will try to see if upgrading the dependencies can help with some of said issues.
> upgrading gcp dependencies in package

- packages/gcp/package.json
- packages/gcp/src/BigQueryClient.ts
While inserting data into big query, it sends a response back if there's an error. This can be extremely helpful while debugging
> Log out a detailed error msg while inserting data into big query

- packages/grpc/package.json
- packages/grpc/src/internal/GrpcInputSource.ts
- packages/grpc/src/internal/client.ts
This PR is attempting to fix issue #211 where the performance timing being passed in is in millisecs whereas the underlying metric collector expects the unit to be seconds.
I'm not sure if the fix is too restrictive in a sense that we might not be able to instrument in millisecs if we wanted to later on. Perhaps, a better fix is in the following `timing` function?
https://github.com/walmartlabs/cookie-cutter/blob/52aaa98ea418c2e8be923f574c5d19ae23fbd563/packages/prometheus/src/index.ts#L142
> Fixed issue with wrong grpcClient timing metric's unit

- packages/kafka/package.json
- packages/kafka/src/index.ts
- packages/prometheus/package.json
- packages/prometheus/src/index.ts
`IPrometheusConfiguration` and `IRawKafkaMessage` should be part of the public API.
> Add missing Kafka and Prometheus exports

- packages/redis/package.json
- packages/redis/src/RedisStreamSource.ts
We use XREADGROUP for redis stream and that has a known side effect where sometimes server is yet not sure if a message was processed at least once and in that case already processed messaged are picked up and since those do not exist in PEL, ack would fail. In our case we are seeing that when this happens then instead of just skipping the failed ack message cc app gets stuck and we eventually loose consumer group. This change is to throw an error in case ack fails so app does not get stuck.
> Redis Stream: Fix source halts

- packages/core/package.json
- packages/core/src/__test__/internal/helpers.test.ts
- packages/core/src/internal/CompositeInputSource.ts
- packages/core/src/internal/helpers.ts
We have seen an issue where in case of an error being thrown for a cc app with composite input source that error is ignored and we keep running the app without the input source with issue which is not what we always want to do. We only got to know about this issue after we attached a remote debugger to our app in production. This change is to get some logs to easily identify and eventually remediate this issue with composite input source.
> Add logs to composite input source to debug lost sources

- packages/kafka/package.json
- packages/kafka/src/KafkaSource.ts
- packages/kafka/src/__test__/KafkaSource.test.ts
- packages/kafka/src/__test__/config.test.ts
- packages/kafka/src/config.ts
- packages/kafka/src/index.ts
Sometimes messages that were produced by another system have additional information as part of the message headers.  There is a need to propagate that information as part of message metadata.  This PR allows users to specify additional header names that could be added to message metadata.
> Added ability to pull custom message headers into message metadata for kafka

- packages/grpc/package.json
- packages/grpc/src/internal/GrpcInputSource.ts
Peer is creating a bunch of cardinality aspects in metrics.  More of a logging thing rather then a metrics.
> Reduce cardinality GRPC peer remove from metrics

- packages/gcp/package.json
- packages/gcp/src/GcsClient.ts
- packages/gcp/src/__test__/GcsClient.test.ts
- packages/gcp/src/index.ts
- yarn.lock
**Testing**
I was able to successfully stream a video into GS.
> Allowing streams for large uploads to google storage via the GCS client

- packages/core/package.json
- packages/core/src/__test__/Application.test.ts
- packages/core/src/internal/ApplicationBuilder.ts
- packages/core/src/internal/processor/ConcurrentMessageProcessor.ts
- packages/core/src/internal/processor/IMessageProcessor.ts
- packages/core/src/internal/processor/SerialMessageProcessor.ts
- packages/core/src/model/dsl.ts
- packages/core/src/model/metrics.ts
- packages/core/src/utils/BoundedPriorityQueue.ts
This health check will enable applications to auto heal/log if input queue of cc is full and no new messages from it are being processed for certain amount of time. It could be used as a guard for apps using kafka, redis, etc. and would be particularly helpful for kafka sources where we have a known issue because of cookie cutter uses sync callback to implement synchronization barrier for post rebalance async calls which sometimes causes consumers to be lost. Kafka JS has an open issue to add support for async callbacks but until that is done, this health check will help. Similarly it would be a good guard to add for apps with redis source as well.
> Add cc health check to prevent stuck apps for any input sources
